title: OFFERMASTER 全球留学
description: 专业留学服务，助你拿下世界名校 offer
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

# 允许 Jekyll 处理 pages 文件夹
collections:
  pages:
    output: true
    permalink: /:name.html
